spring: 
  application:
    name: springCloud-provider-ribbon
    
server:
  port: 8102
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    appname: MOVIE-CONSUMER-RIBBON

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://user:password123@localhost:8761/eureka
#  instance:
#      appname: MOVIE-CONSUMER-RIBBON
