server:
  port: 8105
spring:
  application:
    name: feign

eureka:
  client: 
    serviceUrl:
      defaultZone: http://39.108.125.41:8761/eureka
  instance:
    appname: feign-service
ribbon:
  eager-load:
    enabled: false