server:
  port: 8105
spring:
  application:
    name: mc-feign

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: feign-service

ribbon:
  eager-load:
    enabled: false