server:
  port: 8081
  servlet:
    path: /

spring:
  application:
    name: spring-cloud-stream
  rabbitmq:
    host: localhost
    port: 5672
    username: cloud
    password: xxxx
    virtual-host: /cloud
  cloud:
    stream:
      bindings:
        input1:
          destination: wdtest1
          content-type: application/json
          group: g1
        input2:
          destination: wdtest2
          content-type: application/json
          group: g1
        input3:
          destination: wdtest3
          content-type: application/json
          group: g1
        input4:
          destination: wdtest4
          content-type: application/json
          group: g1


eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"