server:
  port: 8001
  
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
#    ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.name}:${server.port}
    metadata-map:       #自定义元数据
      zone: ABC
      ruolin: BBC
    lease-renewal-interval-in-seconds: 5
#    appname: USER-SERVICE-HAHA
#    hostname: user
    
      
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.description.sql.BasicBinder: TRACE
    org.hibernate.type.description.sql.BasicExtractor: TRACE
    com.jja: DEBUG
    
spring:
  application:
    name: springCloud-provider
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: root
    
    